### ISSUE TITLE
Todo in Algebra

### ISSUE THREAD

**Issue by inakleinbottle** [datasig-ac-uk/RoughPy#1]
- [ ] Implement algebra bundle traits
- [ ] use traits to get bundle size.
- [ ] use traits to get bundle dimension.
- [ ] Implement algebra bundle width
- [ ] Implement algebra bundle depth
- [ ] Implement get and get_mut for algebra bundles
- [ ] More robust compatibility checking for contexts
   * check width is the same, and the scalar types compatible
   * Support checking different configurations such as exact, or same device, etc.
   * Support convertible to and from.
- [ ] Implement Lie to tensor and tensor to Lie fallbacks. Or maybe remove them.
- [ ] Lite context should not make use of any fallback methods. Implement any remaining methods
- [ ] Lite context convert_impl needs to be implemented.
- [ ] Re-implement priority system for getting/creating contexts.
- [ ] Add tests for all the basic functions.
- [x] Add lite context for polynomial coefficients
