### ISSUE TITLE
TODO in scalars

### ISSUE THREAD

**Issue by inakleinbottle** [datasig-ac-uk/RoughPy#2]
- [ ] Finish off the scalar matrix class
- [ ] Look at the ScalarArray and OwnedScalarArray, it might be good to unify these.
- [ ] Blas implementations need a lot of work
- [ ] Integrate the basic integer flags into the scalar type checking
- [ ] Finish the ring characteristics for scalar types
- [ ] Implement Eigen-based blas/lapack
- [ ] Implement Scalar::is_zero
- [ ] Check the Scalar::set_to_zero logic.
- [ ] Implement get_type for string+device
- [ ] Add device getter to scalar type
