### ISSUE TITLE
Pad out API Reference page

### ISSUE THREAD

**Issue by philipparubin** [datasig-ac-uk/RoughPy#89]
# TODOs for API Reference

### Contexts

- [x] Context class

  - [x] top level
  - [x] cbh (computes the cbh product of a number of lie elements within that context, using the truncation levels. Lies need to have the same width, but truncation level might differ)
  - [x] compute_signature (computes the signature of a stream)
  - [x] ctype (coefficient type - one of the RoughPy ones (rp.SPReal, rp.DPReal, rp.Rational, rp.PolyRational))
  - [x] depth (maximum degree for Lies, tensors, etc. (deprecated, use ctx instead))
  - [x] lie_basis (an instance of lie basis with the context's width and depth)
  - [x] lie_size (a shortcut for lie_basis.size)
  - [x] lie_to_tensor (linear embedding of the lie algebra into the free tensor algebra)
  - [x] tensor_basis (an instance of tensor basis with the context's width and depth)
  - [x] tensor_size (a shortcut for tensor_basis.size)
  - [x] tensor_to_lie (inverse of above)
  - [x] to_logsignature (takes some arg (signature), equivalent to tensor_to_lie(signature.log()))
  - [x] width (alphabet size, dimension of the underlying space (deprecated, use ctx instead))
  - [x] zero_lie

- [x] Other

  - [x] get_context (takes width depth coeff as minimum, returns a context with that config, has other keywords that aren't fully realised yet)
  
---

### Streams

- [x] Stream class

  - [x] top level
  - [x] ctx (provide an algebra context in which to create the algebra)
  - [x] dtype (maximum degree for Lies, tensors, etc.)
  - [x] logsignature
  - [x] resolution (resolution for the dyadic dissection of the domain, and the default resolution used in signature/log_signature calculations.)
  - [x] restrict
  - [x] signature
  - [x] signature_derivative
  - [x] simplify
  - [x] support (interval of parameter values on which the stream has meaning.)
  - [x] width (alphabet size, dimension of the underlying space)

- [ ] StreamSchema *LOW PRIORITY*

  - [ ] top level (A translation between input data and stream data.)
  - [ ] from_data
  - [ ] get_labels
  - [ ] insert_categorical
  - [ ] insert_increment
  - [ ] insert_value
  - [ ] parse
  - [ ] width

- [ ] Other

  - [x] StreamInterface
  - [ ] TickStream *Low priority*
  - [x] TickStreamConstructionHelper (Helps the stream figure out what its schema should be. A means of constructing the schema for a stream)
  - [x] PiecewiseAbelianStream
  - [x] LieIncrementStream
  - [x] FunctionStream
  - [x] ExternalDataStream
  - [x] BrownianStream

---

### Intervals

- [ ] Interval class

  - [x] top level
  - [x] contains (takes either a number, tells you if it's there or not, OR takes an interval, tells you if that interval is fully contained in the other interval)
  - [x] excluded_end
  - [x] included_end
  - [x] inf
  - [x] intersects_with (do they overlap)
  - [x] interval_type
  - [x] sup

- [ ] DyadicInterval

  - [x] top level (could be improved)
  - [x] dyadic_excluded_end
  - [x] dyadic_included_end
  - [x] dyadic_inf
  - [x] dyadic_sup
  - [x] shrink_left (split in half, take the left)
  - [x] shrink_right (split in half, take the right)
  - [x] shrink_to_contained_end (same as above, aware of the type... clopen, openCL...)
  - [x] shrink_to_omitted_end (same as above, aware of the type)
  - [x] to_dyadic_intervals

- [ ] Other

  - [x] check formatting - build issues
  - [x] IntervalType (either clopen or OpenCL ...  although only clopen supported currently)
  - [x] RealInterval
  - [x] DateTimeInterval (an interval which describes a region of time)

---

### Free Tensors

- [ ] FreeTensor class

  - [x] check formatting on this section, building issues
  - [x] top level
  - [x] add_mul (Adds to the instance a product of algebra instances.)
  - [x] add_scal_div (A version of += fused with rational division)
  - [x] add_scal_mul (A version of += fused with scalar multiplication)
  - [x] antipode (Computes the antipode of a free_tensor instance.)
  - [x] context (provide an algebra context in which to create the algebra)
  - [x] degree (what we have, not fixed, less than or equal to depth)
  - [x] dimension (the number of elements that are represented by the vector)
  - [x] exp (Computes the truncated exponential of a free_tensor instance.)
  - [x] fmexp (Fused multiply exponential operation for free tensors. Computes a*exp(x).)
  - [x] log (Computes the truncated log of arg up to degree max_degree)
  - [x] max_degree (set out by the basis, i.e. depth)
  - [x] size (total number of non-zero elements represented by the vector, measure of sparsity)
  - [x] storage_type (sparse or dense)
  - [x] sub_mul (Subtracts to the instance a product of algebra instances.)
  - [x] sub_scal_div (A version of -= fused with rational division)
  - [x] sub_scal_mul (A version of -= fused with scalar multiplication)
  - [x] width (alphabet size, dimension of the underlying space (deprecated, use ctx instead))

- [ ] TensorKey *low priority*

  - [ ] top Level (tensor words)
  - [ ] basis 
  - [ ] degree
  - [ ] max_degree
  - [ ] reverse
  - [ ] split_n
  - [ ] to_index
  - [ ] to_letter
  - [ ] width

- [ ] TensorBasis

  - [x] check this section for formatting
  - [ ] top level (fundamental basis, standard basis of the tensor algebra for a given alphabet size and truncation level)
  - [x] depth (trucation level)
  - [x] index_to_key (integer > key at that index)
  - [x] key_to_index (reverse)
  - [x] parents (splits of the first letter returns the letter and the remainder of the word)
  - [x] size (how big the dimension will be at a particular degree)
  - [x] width (alphabet size)

- [ ] Other

  - [ ] TensorKeyIterator (kill off)
  - [ ] FreeTensorIteratorItem (kill off)

---

### Shuffle Tensors

- [ ] Shuffle Tensor Class

  - [x] check formatting on this section, building issues
  - [x] top level
  - [x] add_mul (Adds to the instance a product of algebra instances.)
  - [x] add_scal_div (A version of += fused with rational division)
  - [x] add_scal_mul (A version of += fused with scalar multiplication)
  - [x] context (provide an algebra context in which to create the algebra)
  - [x] degree (what we have, not fixed, less than or equal to depth)
  - [x] dimension (the number of elements that are represented by the vector)
  - [x] dtype (scalar type for the algebra (deprecated, use ctx instead). Can be a RoughPy data type (rp.SPReal, rp.DPReal, rp.Rational, rp.PolyRational), or a numpy dtype.)
  - [x] is_zero (bool, check if empty)
  - [x] max_degree (set out by the basis, i.e. depth)
  - [x] mul_sdiv (multiply and scalar divide)
  - [x] mul_smul (multiply and scalar multiply)
  - [x] size (total number of non-zero elements represented by the vector, measure of sparsity)
  - [x] storage_type (sparse or dense)
  - [x] sub_mul (Subtracts to the instance a product of algebra instances.)
  - [x] sub_scal_div (A version of -= fused with rational division)
  - [x] sub_scal_mul (A version of -= fused with scalar multiplication)
  - [x] width (alphabet size, dimension of the underlying space (deprecated, use ctx instead))

- [ ] Other

  - [x] Check formatting - build issues
  - [ ] ShuffleTensorIteratorItem (kill off)
  - [x] half_shuffle_multiply (half shuffle two shuffle tensors, etc. Do what's not allowed by type (ish). Use a multiplication that isn't the native one)
  - [x] shuffle_multiply (Shuffle two free tensors. Use a multiplication that isn't the native one)

---

### Lies

- [ ] Lie class

  - [x] check formatting on this section, building issues
  - [x] top level (needs tidying)
  - [x] add_mul (Adds to the instance a product of algebra instances.)
  - [x] add_scal_div (A version of += fused with rational division)
  - [x] add_scal_mul (A version of += fused with scalar multiplication)
  - [x] context (provide an algebra context in which to create the algebra)
  - [x] degree (what we have, not fixed, less than or equal to depth)
  - [x] dimension (the number of elements that are represented by the vector)
  - [x] dtype (scalar type for the algebra (deprecated, use ctx instead). Can be a RoughPy data type (rp.SPReal, rp.DPReal, rp.Rational, rp.PolyRational), or a numpy dtype.)
  - [x] is_zero (bool, check if empty)
  - [x] max_degree (set out by the basis, i.e. depth)
  - [x] mul_sdiv (multiply and scalar divide)
  - [x] mul_smul (multiply and scalar multiply)
  - [x] size (total number of non-zero elements represented by the vector, measure of sparsity)
  - [x] storage_type (sparse or dense)
  - [x] sub_mul (Subtracts to the instance a product of algebra instances.)
  - [x] sub_scal_div (A version of -= fused with rational division)
  - [x] sub_scal_mul (A version of -= fused with scalar multiplication)
  - [x] width (alphabet size, dimension of the underlying space (deprecated, use ctx instead))

- [ ] LieBasis (same as tensor basis)

  - [x] check this section for formatting
  - [ ] top level
  - [x] depth
  - [x] dimension
  - [x] index_to_key
  - [x] key_to_index
  - [x] parents
  - [x] size
  - [x] width

- [ ] Other

  - [ ] LieIteratorItem (kill off)
  - [x] LieKey (same as a tensor key, Hall word, element of the Hall basis for the free Lie algebra)
  - [ ] LieKeyIterator (kill off)

---

## Other parts to consider, which are blank on the page

- [ ] ChannelType (belongs with schema, a schema is a sequence of channel types) *low priority*

- [ ] Partition (members) (an interval into which there are a number of intermediate points which represent the end points of sub intervals)
  - [x] check this section for formatting 
  - [x] insert_intermediate (cuts one of the intermediate intervals in half)
  - [x] intermediates (list of intermediate end points)
  - [x] merge (the union of the partitions)
  - [x] mesh (length of the largest sub interval)
  - [x] refine_midpoints (inserts the midpoint between all of the intermediates)

- [ ] Monomial

- [ ] VectorType

- [x] adjoint_to_free_multiply (performs the adjoint of the free multiplication, A>A)

- [ ] Dyadic (members) (a number of the form k/(2^n)
  - [x] check formatting 
  - [x] dyadic_equals (check if two dyadic rationals are equivalent, k1=k2,n1=n2)
  - [x] rational_equals k1/(2^(n1)) = k2/(2^(n2)) as rational numbers, e.g. 2/2^1 = 1/2^0 as rationals, but not as dyadics

---

## Look less important, but check

These are the currently supported scalar types in RoughPy. These are mostly needed for the dtype in constructor methods
- [ ] DPReal
- [ ] HPReal
- [ ] SPReal
- [ ] Rational
- [ ] RationalPoly
- [ ] bfloat16

Proxy object for an element in one of the roughpy algebra objects
- [ ] Scalar

Things that people should never look at!
- [ ] ScalarMeta
- [ ] ScalarTypeBase
